### PR TITLE
Update to work with dual UR10 in ARIAC 2019

### PR DESCRIPTION
**Pull request by rmerriam**
Signed-off-by: Shane Loretz <sloretz@osrfoundation.org>

### CODE REVIEW

**Comment by rmerriam** [comment]
update to ur

**Comment by sloretz** [comment]
Hi @rmerriam , it looks like the branch `ariac_2019_ur10_moveit_config` [already has these changes](https://github.com/osrf/universal_robot/commits/ariac_2019_ur10_moveit_config ) in commit: 8bb711dc9f81087306ae962f9e251e69dc31721d . I'm surprised the github UI shows anything under `Files changed`. Would you mind explaining what this PR does?

**Comment by rmerriam** [comment]
This can be deleted. 

I forked UR to my github. Actually want to delete it now because I adopted a different approach. But can't see how to delete this or my fork.

**Comment by sloretz** [comment]
I'll close this PR then. Here's a link to how to delete a repository on github: https://help.github.com/en/articles/deleting-a-repository

**Comment by rmerriam** [comment]
I found the repo delete in settings. Thanks.

**Pull request closed without merging**
